import { create } from "zustand";
import * as fabric from "fabric";
import type { Canvas, FabricObject } from "fabric";

const ZOOM_MIN  = 0.05;
const ZOOM_MAX  = 20;
const ZOOM_STEP = 1.25;
const MAX_HISTORY = 50;

// ── Types ─────────────────────────────────────────────────────────────────────

export type EditorMode = "design" | "preview";
export type ToolId = "select" | "rectangle" | "ellipse" | "line" | "text" | "pan" | "pen";

export type AnchorH = "left" | "center" | "right";
export type AnchorV = "top"  | "middle" | "bottom";
export interface AnchorPoint { x: AnchorH; y: AnchorV; }

export interface EditorState {
  canvas: Canvas | null;
  selectedObjects: FabricObject[];
  zoom: number;
  mode: EditorMode;
  activeTool: ToolId;

  /**
   * PNG data URL generated by generateThumbnail().
   * Null until the user explicitly captures a preview.
   * Read by cart / order components to attach the design image.
   */
  designThumbnail: string | null;

  // ── Transform panel ───────────────────────────────────────────────────────
  /** Which of the 9 reference points is used for X/Y positioning. Persists across selection changes. */
  transformAnchor: AnchorPoint;
  /** When true, W and H scale together to preserve aspect ratio. */
  transformLockAspect: boolean;

  // ── History ──────────────────────────────────────────────────────────────
  /** Serialized canvas snapshots (most recent at the end). */
  history: string[];
  /** Index of the currently displayed snapshot (-1 = empty). */
  historyIndex: number;
  /** Guards against recording snapshots while undo/redo is restoring state. */
  isRestoringHistory: boolean;
  /** When true, automatic event-based snapshot recording is suppressed. */
  historyPaused: boolean;
}

export interface EditorActions {
  setCanvas: (canvas: Canvas | null) => void;
  setSelectedObjects: (objects: FabricObject[]) => void;
  setZoom: (zoom: number) => void;
  setMode: (mode: EditorMode) => void;
  setActiveTool: (tool: ToolId) => void;
  setDesignThumbnail: (dataUrl: string | null) => void;
  zoomIn: () => void;
  zoomOut: () => void;
  setTransformAnchor: (anchor: AnchorPoint) => void;
  setTransformLockAspect: (locked: boolean) => void;

  // ── History ──────────────────────────────────────────────────────────────
  /**
   * Appends a snapshot to the history stack.
   * No-ops when `isRestoringHistory` or `historyPaused` is true.
   */
  pushHistory: (snapshot: string) => void;
  /** Suppress automatic event-based snapshot recording. */
  pauseHistory: () => void;
  /** Resume automatic event-based snapshot recording. */
  resumeHistory: () => void;
  /**
   * Capture the current canvas state and force-push it to the history stack.
   * Bypasses `isRestoringHistory` and `historyPaused` guards.
   * Use after batch operations (alignment, grouping, property changes).
   */
  takeSnapshot: () => void;
  /** Restore the previous canvas state. */
  undo: () => Promise<void>;
  /** Restore the next canvas state (after an undo). */
  redo: () => Promise<void>;
}

// ── Store ─────────────────────────────────────────────────────────────────────

export const useEditorStore = create<EditorState & EditorActions>((set, get) => ({
  // ── Initial state ─────────────────────────────────────────────────────────
  canvas: null,
  selectedObjects: [],
  zoom: 100,
  mode: "design",
  activeTool: "select",
  designThumbnail: null,

  transformAnchor: { x: "center", y: "middle" },
  transformLockAspect: false,

  history: [],
  historyIndex: -1,
  isRestoringHistory: false,
  historyPaused: false,

  // ── Actions ───────────────────────────────────────────────────────────────
  setCanvas: (canvas) => set({ canvas }),
  setSelectedObjects: (selectedObjects) => set({ selectedObjects }),
  setZoom: (zoom) => set({ zoom }),
  setMode: (mode) => set({ mode }),
  setActiveTool: (tool) => set({ activeTool: tool }),
  setDesignThumbnail: (dataUrl) => set({ designThumbnail: dataUrl }),
  setTransformAnchor: (anchor) => set({ transformAnchor: anchor }),
  setTransformLockAspect: (locked) => set({ transformLockAspect: locked }),

  zoomIn: () =>
    set((state) => {
      if (!state.canvas) return {};
      const c = state.canvas;
      const z = Math.min(ZOOM_MAX, c.getZoom() * ZOOM_STEP);
      const center = c.getCenterPoint();
      c.zoomToPoint(new fabric.Point(center.x, center.y), z);
      return { zoom: Math.round(z * 100) };
    }),

  zoomOut: () =>
    set((state) => {
      if (!state.canvas) return {};
      const c = state.canvas;
      const z = Math.max(ZOOM_MIN, c.getZoom() / ZOOM_STEP);
      const center = c.getCenterPoint();
      c.zoomToPoint(new fabric.Point(center.x, center.y), z);
      return { zoom: Math.round(z * 100) };
    }),

  // ── History actions ───────────────────────────────────────────────────────

  pushHistory: (snapshot) => {
    const { isRestoringHistory, historyPaused } = get();
    if (isRestoringHistory || historyPaused) return;

    set((state) => {
      // Drop any "future" snapshots when a new action is taken after an undo
      const base = state.history.slice(0, state.historyIndex + 1);
      base.push(snapshot);
      // Trim to MAX_HISTORY
      const trimmed = base.length > MAX_HISTORY
        ? base.slice(base.length - MAX_HISTORY)
        : base;
      return { history: trimmed, historyIndex: trimmed.length - 1 };
    });
  },

  pauseHistory: () => set({ historyPaused: true }),
  resumeHistory: () => set({ historyPaused: false }),

  takeSnapshot: () => {
    const { canvas } = get();
    if (!canvas) return;
    const raw = canvas.toJSON() as {
      objects?: Array<{ data?: { tag?: string }; excludeFromExport?: boolean }>;
    };
    if (raw.objects) {
      raw.objects = raw.objects.filter(
        (o) =>
          !o.excludeFromExport &&
          o.data?.tag !== "__snap_guide__" &&
          o.data?.tag !== "__pen_preview__",
      );
    }
    const json = JSON.stringify(raw);
    // Force-push — bypasses isRestoringHistory and historyPaused
    set((state) => {
      const base = state.history.slice(0, state.historyIndex + 1);
      base.push(json);
      const trimmed = base.length > MAX_HISTORY
        ? base.slice(base.length - MAX_HISTORY)
        : base;
      return { history: trimmed, historyIndex: trimmed.length - 1 };
    });
  },

  undo: async () => {
    const { canvas, history, historyIndex, isRestoringHistory } = get();
    if (!canvas || historyIndex <= 0 || isRestoringHistory) return;

    const newIndex = historyIndex - 1;
    set({ isRestoringHistory: true });
    try {
      await canvas.loadFromJSON(JSON.parse(history[newIndex]));
      canvas.requestRenderAll();
      set({ historyIndex: newIndex });
    } finally {
      set({ isRestoringHistory: false });
    }
  },

  redo: async () => {
    const { canvas, history, historyIndex, isRestoringHistory } = get();
    if (!canvas || historyIndex >= history.length - 1 || isRestoringHistory) return;

    const newIndex = historyIndex + 1;
    set({ isRestoringHistory: true });
    try {
      await canvas.loadFromJSON(JSON.parse(history[newIndex]));
      canvas.requestRenderAll();
      set({ historyIndex: newIndex });
    } finally {
      set({ isRestoringHistory: false });
    }
  },
}));
